// VTuber-start/VTuber-Angular/src/app/vtuber/vtuber-entity/vtuber-entity.component.ts
import { Component, Input } from '@angular/core';
import { VTuber } from '../../models/vtuber'; // Make sure this import path is correct

@Component({
  selector: 'vtuber-entity',
  standalone: true,
  templateUrl: './vtuber-entity.component.html',
  styleUrls: ['./vtuber-entity.component.scss']
})
export class VtuberEntityComponent {
  @Input() vtuberEntity!: VTuber;  // Ensure this is the correct property name and type
}

<div class="bg-white rounded-xl shadow-md relative">
  <div class="p-4">
    <div class="mb-6">
      <div class="text-gray-600 my-2"> {{ vtuberEntity.name }} </div>
      <div class="name-line"></div>
    </div>
    <div class="border border-gray-100 mb-5"></div>
  </div>
</div>

// BetterFront-start/BetterFront-React/src/pages/Tables/VTuber/VTuberEntity.tsx
import { VTuber } from '../../../models/VTuber';

const VTuberEntity = ({ vtuber }: { vtuber: VTuber }) => {
  return (
    <>
      <div className="bg-white rounded-xl shadow-md relative">
        <div className="p-4">
          <div className="mb-6">
            <div className="text-gray-600 my-2">{vtuber.name}</div>
          </div>
          <div className="border border-gray-100 mb-5"></div>
        </div>
      </div>
    </>
  );
};

export default VTuberEntity;
